main:
  - name: Source Code
    identifier: source
    url: https://github.com/liluzibird/blog
    params:
      icon: '<i class="fab fa-github"></i>'
  # - name: My Website
  #   identifier: site
  #   url: 
  #   params:
  #     icon: '<i class="fas fa-globe"></i>'
  # - name: RSS
    # identifier: rss
    # url: /index.xml
    # params:
      # icon: '<i class="fas fa-rss"></i>'
  - name: Comments
    identifier: comments    
    weight: 9
    url: https://github.com/liluzibird/blog/discussions/categories/giscus
    params:
      icon: '<i class="fas fa-comments"></i>'
  - name: About
    identifier: About
    weight: 10
    url: /about
    params:
      icon: '<i class="fas fa-info-circle"></i>'
  - name: Contact
    identifier: contact
    url: /contact
    params:
      icon: '<i class="fas fa-envelope"></i>'
  # - name: Copyright
    # identifier: copyright
    # url: /about#copyright
    # params:
      # icon: '<i class="far fa-copyright"></i>'
